### ISSUE TITLE
add .gitignore 

### ISSUE THREAD

**Issue by sudhanshu-chauhan** [ritwik12/Celestial-bodies-detection#17]
while cloning the code, I found a .pyc file in the master branch! I feel like we should add a .gitignore file and add pyc file in it! please let me know if it sounds like a good idea, I will raise a PR for the same via separate branch

**Comment by ritwik12** [comment]
@sudhanshu-chauhan Thanks for pointing it out. Please send PR

**Comment by sudhanshu-chauhan** [comment]
done!
