### ISSUE TITLE
Change Training data filenames

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#37]
As of now all the files inside the training data are random names and most are the names of the objects which they are like "earth", "mars" etc which makes it look bad as we are classifying images here. Better to have names in numeric order like 01, 02, 03 and so on.

PS: It will require a script to change the names of files, don't do it manually :p

**Comment by attard-andrew** [comment]
Hi,

This will be the FIRST EVER issue I will attempt to assist with. I believe I can do it, though I haven't quite learned how contributing exactly works yet - but I will Google my way to an answer soon. Once I figure that out, I believe I can handle the renaming no problem :).  I just want to clarify the requirements.

- I see that the training data are grouped according to celestial body - you mention that these should be numbered.  Should the parent folder's associated celestial body be included in the filename? For example:

mars_01
mars_02

or

01_mars
02_mars

or simply

01
02
03

**Comment by kannandreams** [comment]
I would like to pick this enchancement and fix the file name convention by utilitiy module. I will share the design approach at earliest.

**Comment by kannandreams** [comment]
Missed the chance :( . lets @attard-andrew work on it.  Thanks.

**Comment by ritwik12** [comment]
@kannandreams We have a lot of work to do here, this is a really good field for Research work also as it is never done before. I will add more issues for you to grab.

**Comment by ritwik12** [comment]
@attard-andrew 
```
01
02
03
```
is good as we don't want users to give a perception that their is already a name of the object  that we want to classify like say "Mars". so why to classify? for AI folks that's easily understandable but not for everyone. so we should have names of images as generic only inside training data as well as test data. Better to create directories inside test data as well and follow same pattern

**Comment by ritwik12** [comment]
Hope you got my point

**Comment by attard-andrew** [comment]
> @attard-andrew
> 
> ```
> 01
> 02
> 03
> ```
> 
> is good as we don't want users to give a perception that their is already a name of the object that we want to classify like say "Mars". so why to classify? for AI folks that's easily understandable but not for everyone. so we should have names of images as generic only inside training data as well as test data. Better to create directories inside test data as well and follow same pattern

Makes sense! I'm having some issues but hoping to figure out by the end of today.  I'm attempting to use os.walk to go through all the directories and increment their filenames using a loop & os.replace() though - I might attempt shutil.move.

I'll let you know how it goes!

**Comment by attard-andrew** [comment]
Hi @ritwik12 

I believe I've completed the task and am ready to submit a pull request.  When going to submit the request - it said that the changes would be automatically merged.  Since I am still unfamiliar with this workflow & the implications of automatically merging new code  - I wanted to confirm here first if it's ok to move ahead.

My assumption is that it will do exactly as it sounds & auto merge any changes - including any potential (accidental) image or file deletions that I may have made due to inexperience.  Though I also assume that any impact could easily be rolled back - correct?

Anyway - once I have confirmation I'll submit the pull request here :)

**Comment by ritwik12** [comment]
Hey, How are you creating the changes? Using git or Github?
Please share the screenshot of what you are seeing.

**Comment by attard-andrew** [comment]
The workflow I followed is:

- Forked your repo
- Cloned to my local machine
- Created a branch called 'rename_training_images'
- Created a file called 'rename_training_files.py' that goes over all training images and moves them to a new folder called 'new_training_images', number all files from 0 up
- Commit the changes & pushed my branch
- Came to my forked repo on the Github website and clicked "Compare & pull request"
- Arrived at the below, though I realize now it says that it **can** be merged automatically not that it **will be**. Still do not want to assume that GIthub interprets the same way I interpret that statemetn

![image](https://user-images.githubusercontent.com/54812701/68389006-7f416080-0194-11ea-94f1-be3c4210ae6e.png)

**Comment by ritwik12** [comment]
@attard-andrew  That's good and this is the way to do it, it just stats that these branches can be merged as there are no merge conflicts in this. Sometimes you can also open a PR from a branch that is not even of that project. there it will not allow you to open PR.

Also, please add the script in utils directory by creating a new directory called utils outside in the main directory with README.md and give it the name `rename_files.py`.

**Comment by ritwik12** [comment]
@attard-andrew Send PR please

**Comment by attard-andrew** [comment]
@ritwik12 done!

**Comment by ritwik12** [comment]
Solved by #42
