### ISSUE TITLE
Get as much information as possible from a image

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#4]
Celestial Images can tell lots of important things such as 

- [x] Distance from Earth

- [x] Composition ( Such as Terrestrial or Jovian, etc)

- [x] Size

and many more.

**Comment by iiSindhuii** [comment]
@ritwik12 All this will be a part of the information displayed after the image is classified? If yes, I'd like to take this up.

**Comment by ritwik12** [comment]
@iiSindhuii  It can go that way too. Please give it a try. Please create an separate issue and also mention checkpoints on what you will be adding to that PR.

**Comment by hemanthsavasere** [comment]
@ritwik12 I want to work on this issue. Since nobody has mentioned anything about it after Feb 19

**Comment by ritwik12** [comment]
@hemanthsavasere Sure, please do.

**Comment by ritwik12** [comment]
Solved in #7
