### ISSUE TITLE
Classify Asteroids

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#41]

**Comment by Dhammer3** [comment]
Hi, I would like to work on this issue.

**Comment by ritwik12** [comment]
@Dhammer3 Sure, please go ahead

**Comment by Dhammer3** [comment]
let me know if there is anything that needs to be fixed :)

**Comment by ritwik12** [comment]
@Dhammer3 I have reviewed. Please check.

**Comment by dejesusj** [comment]
Is this still open, if so, I'd like to work on the issue.

**Comment by ritwik12** [comment]
Yes @dejesusj Please feel free to.

**Comment by Zignake** [comment]
Hey, can I get to know a bit more regarding what exactly has to be done?

**Comment by ritwik12** [comment]
@Zignake Sure, If you go through the project. You would notice that we are trying to classify the Images as per the Celestial Object like Moon, Earth, Venus, Spiral galaxy and soo on. Just like that Asteroid will be an addition to the categories and one needs to add the training and testing data images to train the model for Asteroids. you can go through other PRs like the one which included Moon to know more and how to do it.

**Comment by Zignake** [comment]
@ritwik12  I saw the commit made for adding images of Uranus #71 . Just confirming that I just have to add images for training and testing and not making any changes in the code right? And also is there any specific resolution of images to be added or any (that are clear) is fine?

**Comment by ritwik12** [comment]
@Zignake Look at #26, for the CNN model you don't need to change anything as the Model takes care of that. But If you are interested in learning I would advise you to go through the code to learn how it all actually works. 

For adding new category just add new images and a few edits in the scripts would do that.

No, there is no specific resolution, the model takes care of all that in pre-processing where it reforms the data. However it should be clear and a genuine one without having any Noise(simple clear Image).

**Comment by Zignake** [comment]
@ritwik12 Okay, thanks.

**Comment by Zignake** [comment]
@ritwik12 For the display_info.yml file, I have mentioned and put in the info of the Asteroid Belt only and not the Kuiper Belt. Please let me know if anything is to be done.

**Comment by ritwik12** [comment]
#72
