### ISSUE TITLE
Change Test data files names

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#45]
It will be good to have test data the same way we have training data in specific folders with proper numbering like 000, 001 etc

**Comment by ritwik12** [comment]
There is a script contributed by @attard-andrew `/utils/rename_files.py ` which can be used

**Comment by attard-andrew** [comment]
@ritwik12 Submitting pull request now.

**Comment by ritwik12** [comment]
@attard-andrew Any progress here?

**Comment by Shreya-Pathak** [comment]
Hi! Is this issue still open? I would like to contribute.

**Comment by ritwik12** [comment]
I guess this was already done and missed to close the issue. Closing now!!
