### ISSUE TITLE
Create GUI

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#5]
Right now it is simply terminal based. A good GUI will make it a proper software instead of a mere tool.

**Comment by BreakfastWhisky** [comment]
Would you be alright with a GUI made using PyQt? And are there any specific requirements for this that you have in mind?

**Comment by ritwik12** [comment]
If GUI suites with current code, It should be fine. No idea as suchj, usually personal digital assistant are  of the form of a messenger, reference: https://ritwik12.github.io/assets/pda/index.html

New ideas are great to have, but it would be a big deal to make a GUI for this. Please do it in steps and take reviews after every step so that you will utilize your time better.

**Comment by ritwik12** [comment]
@BreakfastWhisky Thanks for giving a thought.

**Comment by ritwik12** [comment]
PyQt should be good, though haven't used it. Please go with this. Also, please do it in steps and take reviews after few steps to utilize your time better.

**Comment by BreakfastWhisky** [comment]
Hey, so I started to dig into the amount of work actually required to do this well... and I'm going to be lame and back away from this. Sorry!

**Comment by ritwik12** [comment]
@BreakfastWhisky It's fine :)

**Comment by sudhanshu-chauhan** [comment]
@ritwik12 I wanna take up this issue if fine by you! I am thinking of many options, but can be broadly divided into two catagories:
1) a native app like tkinter or qt.
2) webpage using tornado to render (couldn't think of something more minimal and pythonic to handle a webpage)
Please let me know, thanks :)

**Comment by ritwik12** [comment]
@sudhanshu-chauhan That's good to hear. Please go with whatever you are comfortable with or think is better, I guess web page will be much better as it can be deployed easily.

**Comment by KeysonRaphael** [comment]
would like to take care of it

**Comment by ritwik12** [comment]
@KeysonRaphael Please do :)

**Comment by Prakhar314** [comment]
Can I work on this? I'm thinking of using flask to make a webpage.

**Comment by ritwik12** [comment]
@Prakhar314 Please go ahead, share a design doc first before you work for code to understand your design better

**Comment by Prakhar314** [comment]
[Design Doc](https://drive.google.com/file/d/1tWpSP1UE_uGztU54B1px-YRvUB6eRdgr/view?usp=sharing)
Is this ok?

**Comment by ritwik12** [comment]
@Prakhar314 That is really awesome, Can you please add those images and steps in this issue so that we have better accessibility and the design will look good here.

**Comment by ritwik12** [comment]
@Prakhar314 I have assigned this issue to you.

**Comment by ritwik12** [comment]
Closing this with #70. thanks to @Prakhar314 for this contribution.
