### ISSUE TITLE
Refine information displayed about the identified celestial bodies

### ISSUE THREAD

**Issue by Indus5** [ritwik12/Celestial-bodies-detection#6]
Related to #4

**Comment by iiSindhuii** [comment]
@ritwik12 It looks like I don't have access to push to this repository. Can you please provide it?

**Comment by iiSindhuii** [comment]
@ritwik12 It looks like I don't have access to push to the repo. Could you please give me the same?

**Comment by ritwik12** [comment]
@iiSindhuii You need to first fork this repo and then push commits to your own forked repo. After that you need to send a PR from your fork to this repo.
