### ISSUE TITLE
Deploy current webapp to project site

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Celestial-bodies-detection#78]
Need to evaluate different approaches to deploy web app which is a Python-based Flask backend app. The site will be deployed as a project site with `gh-pages` in the form of github.io

**Comment by svshivapuja** [comment]
Hi can I take up this issue ?

**Comment by ritwik12** [comment]
@svshivapuja Sure you can take it up. I am thinking of keeping it open source and using something like Heroku or Firebase.

**Comment by ritwik12** [comment]
This is done with #84 and following instructions to create an app on Heroku and Deploy it.
